### PR TITLE
pOOBAH and sesame by Nathan Steenbuck

### PR DESCRIPTION
**Pull request by schmic05**

### CODE REVIEW

**Comment by schmic05** [comment]
Hi @nathansteenbuck 

I had a look into the code that you wrote. Thanks a lot for providing it. However, I found some issue:

- `detectionPoobEcdf` does not have an parameter `force`
-  `pvalues <- sigset.l[[i]]@pval$pOOBAH` should be `pvalues <- sigset.l[[i]]@pval`
- there are NAs in the vector maskedIDs, which causes these command to fail:

`      nmasked = nmasked + length(mask)
        maskedIDs <- match(mask, probeIDs) 
        raw.set@pval.sites[maskedIDs, i] <- NA
        raw.set@M[maskedIDs, i] <- NA
        raw.set@U[maskedIDs, i] <- NA
        raw.set@M0[maskedIDs, i]<- NA
        raw.set@U0[maskedIDs, i]<- NA`
        
Did you also encounter these problems?

**Comment by nathansteenbuck** [comment]
Hi Michael,

thank you for your quick reply and your effort.

I think these issues have been caused by the version of the dependency
sesame. I had oriented myself on sesame version 1.6, as available by
Bioconductor version 3.11. For that, the wrapper has been working well for
me.
I will try to debug the code so that it has backward compatibility
according to the oldest release that was available through Bioconductor
(i.e. version 3.8), test it and then get back to you.

Best,
Nathan

**Comment by nathansteenbuck** [comment]
Hi Michael,

I added some commits to fix the issues. I think it should work better now
:)

Best regards and have a great start into 2021,
Nathan

**Comment by schmic05** [comment]
Hi @nathansteenbuck 

Thanks for the fixes and for your contribution in general. I merged your branch into the master branch of RnBeads. The function will be available after the next Biocondutor release.

**Pull request merged**
